### ISSUE TITLE
Problem with Imaging Season and high latitudes

### ISSUE THREAD

**Issue by tcpalmer** [tcpalmer/nina.plugin.targetplanning#19]
User occamsrazor reported an exception during Imaging Season calculation.  His latitude is 57.458 and I can duplicate the problem at lat=55 with version 1.2.0.0.  At lat=54, it finishes but with one of those weird periods I started seeing after I installed .Net 7/NINA 3.  But this user hasn't done that.

**Comment by tcpalmer** [comment]
This is due to the fact that at high latitudes as you approach summer solstice, the various twilight time spans become non-existent at some date -> NPE.

**Comment by ben-p-commits** [comment]
that's a pretty cool bug

**Comment by tcpalmer** [comment]
This is due to the fact that at high latitudes as you approach summer solstice, the various twilight time spans become non-existent at some date -> NPE.

**Comment by tcpalmer** [comment]
Fixed on 1.2.1.0
